# Generated by Django 3.1.3 on 2020-11-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'external_users',
            },
        ),
    ]
