# Generated by Django 3.1.3 on 2020-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalusermessages',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
