# Generated by Django 3.1.3 on 2020-11-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_users', '0002_externalusermessages_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusermessages',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='externalusermessages',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
